name: Schedule test

on:
  workflow_dispatch:
  schedule:
    - cron: "3,13,23,33,43,53 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger time
        run: |
          echo "schedule fired"
          date -u
